version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - elasticsearch
      - logstash
      - kibana
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: logging_user
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: logging_db
    ports:
      - "5432:5432"
  elasticsearch:
    image: elasticsearch:7.10.0
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    image: logstash:7.10.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
  kibana:
    image: kibana:7.10.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
